### ISSUE TITLE
Basic Support for Logging

### ISSUE THREAD

**Issue by nobugs-hare** [node-dot-cpp/node.cpp#1]
API: 
- Somehwhat reminiscent of Node.js' Winston, but using levels from syslogd: emerg, alert, crit, err, warning, notice, info, debug
- formatting based on {fmt}
- **adding a new dimension to the logging - 'module'** . Module is an optional StringLiteral first (!) parameter to a log() call; if not specified (which is majority of cases) it defaults to a well-known #define (which can be redefined by end-user). In general, module corresponds to Node, though some libraries MAY specify their own modules.
- **ideally, logger SHOULD be a member of user-defined Node (and NOT of generic Node)** - (a) to facilitate multiple loggers etc., and (b) to be more consistent with Node.js practices.

Implementation: 
- usually completely non-blocking (starting to skip when not able to cope) - unless specified otherwise for a level
- for the time being - supporting only file as a target
- for the time being - no support for filtering.

**Comment by divanchykhin** [comment]
Corrections:
a. Base Node class has a (default) Log which could be used, in particular, by other libraries/modules *within the context of the same Node* (such usage is implemented via a pointer stored in TLS)
b. Node-based classes may have their own Logs.

**Comment by divanchykhin** [comment]
Correction:
a. Levels to use: fatal, err, warning, info, debug
b. Further internal remapping for particular targets (such as syslogd) is possible

**Comment by divanchykhin** [comment]
closed with commit ee85f44
