### ISSUE TITLE
Template-based version of http server

### ISSUE THREAD

**Issue by divanchykhin** [node-dot-cpp/node.cpp#55]
Present version of http server and accompanying objects assumes runtime handler type identification. In the same time, all types are known yet at compile time and, in general, could be passed where needed. As a hinting point a template-based approach for user-def Node class could be taken.

**Comment by nobugs-hare** [comment]
After recent discussions, don't we want to remove template version altogether?

**Comment by divanchykhin** [comment]
Present mechanism of handler registration effectively does the job. Closed.
