### ISSUE TITLE
Separate Dynamical and Template model

### ISSUE THREAD

**Issue by divanchykhin** [node-dot-cpp/node.cpp#56]
From library end user point of view, Dynamical model is user-friendly and does not require any "fancy constructions". In that model registering handles is quite natural, but handler type resolution is done at runtime.
If certain gain in performance is of value, a template version could be used. Here all resolutions are done in compile time (performance gain), but the payment for this is taken in a form of a set of inevitable template type declarations inside a UserNode class.
Handler prototype and implementation remains the same in both models, so switching to template-based model could be performed at any time of development.
Current task is to make sure such models are clearly separated, that is, for instance, if Dynamical model is used, no template constructions are left (by occasion) to the end user to define, etc.
Practically, at present, as a sanity check, tcp server and client projects, and http server sample project must be checked and presented in both versions.

**Comment by nobugs-hare** [comment]
After recent discussions, don't we want to remove template version altogether?

**Comment by divanchykhin** [comment]
Presently existing mechanisms of handling events (lambda- and handler-registering-based) effectively represent what's needed. Closed.
